# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/advent',
                'doc_host': 'https://dijonkitchen.github.io',
                'git_url': 'https://github.com/dijonkitchen/advent',
                'lib_path': 'advent'},
  'syms': { 'advent.2024.1_1': {},
            'advent.2024.1_2': {},
            'advent.2024.2_1': {},
            'advent.2024.2_2': {},
            'advent.2024.3_1': {},
            'advent.2024.3_2': {},
            'advent.2024.4_1': {},
            'advent.2024.4_2': {},
            'advent.core': {'advent.core.foo': ('core.html#foo', 'advent/core.py')}}}
